@startuml
package "Estruturado" {
   node Dados #orange
   node DadosTratados #green
   storage func

   Dados -> func
   func -> DadosTratados
}
package "Orientado a Objetos" {
   rectangle Classe {
   node "Dados" as D #orange
   node Comportamentos #green

   D -> Comportamentos 
   D <- Comportamentos 
}
@enduml